# Generated by Django 5.2.8 on 2025-12-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_jabatanfungsional_jenjangpendidikan_rumpunilmu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajuanbkd',
            name='pengusul',
            field=models.CharField(max_length=255),
        ),
    ]
