# Generated by Django 5.2.8 on 2025-12-22 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_ajuanbkd_pengusul'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajuanbkd',
            name='status_ajuan',
            field=models.CharField(choices=[('proses', 'Proses'), ('disetujui', 'Disetujui')], default='proses', max_length=100),
        ),
    ]
