# Generated by Django 5.2.8 on 2026-01-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ajuanbkd_status_ajuan'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajuanbkd',
            name='surat_penugasan',
            field=models.FileField(blank=True, null=True, upload_to='surat_penugasan/'),
        ),
        migrations.AddField(
            model_name='ajuanbkd',
            name='surat_persetujuan',
            field=models.FileField(blank=True, null=True, upload_to='surat_persetujuan/'),
        ),
        migrations.AlterField(
            model_name='ajuanbkd',
            name='status_ajuan',
            field=models.CharField(choices=[('proses', 'Proses'), ('revisi', 'Revisi'), ('disetujui', 'Disetujui')], default='proses', max_length=100),
        ),
    ]
