# Generated by Django 5.2.8 on 2026-01-12 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_ajuanbkd_surat_penugasan_ajuanbkd_surat_persetujuan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajuanbkd',
            name='jabatanfungsional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.jabatanfungsional'),
        ),
    ]
